name: Docker Image CI

on:
  push:
    branches: [ main ]
jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch

    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.0.1
      with:
        github-token: ${{ secrets.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 }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: calamity_Jen # Provide only Docker image name, tag will be automatically 
        dockerfile: Dockerfile_server
