name: ci

on:
  push:
    branches: [main]
      

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: kyourakou/general/
        registry: docker.io
        username: ${{secrets.docker_user}}
        password: ${{secrets.docker_pass}}